sudo: false

language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

# Use Python 3.7 on xenial with sudo since it's not available on trusty yet
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

env:
  global:
    # List package dependencies for conda (Package, dependency and environment management for any languageâ€”Python: https://docs.conda.io/en/latest/)
    # https://stackoverflow.com/questions/20994716/what-is-the-difference-between-pip-and-conda
    - CONDA_DEPS="pytest numpy"
    # package name for test invocation
    - PACKAGENAME="mvsionedractivityfeed"

#  - pipenv install
#  - pipenv shell

# command to install dependencies
install:
#  - pip install .[test]
  # Install through setup.py should be redundant because of the preceding pip
  # install. Just doing this to try to catch any high-level errors.
#  - python setup.py install
  - pip install pipenv
  - pipenv install
  - pipenv shell


# command to run tests
script:
  #- python setup.py ci
  - python -m tests
